# No git. Let me check if there's a backup or if I can reconstruct the original vectors.
# The original vectors were generated by the golden model with the OLD behavior
# (STOP->IDLE). Since the unit test doesn't have back-to-back frames, the old and
# new golden models produce the SAME output for this test.
# 
# So the vectors I generated should be identical to the original ones... unless
# the golden model has a timing mismatch with the RTL.
#
# Let me check: the test was passing before. The original vectors matched the old RTL.
# My new golden model produces the same output as the old golden model for non-back-to-back
# frames. So my new vectors should be the same as the old vectors.
# 
# But the test is failing! This means either:
# 1. My golden model produces different output than the old one (even for non-back-to-back)
# 2. The old vectors were NOT generated by the golden model
#
# Let me check if the old golden model (STOP->IDLE) produces the same vectors.
# I'll simulate with the old behavior and compare.

import sys
sys.path.insert(0, '.')

# Old uart_tx model (STOP->IDLE, no back-to-back)
from golden.model.baud_gen import BaudGen

class UartTxOld:
    IDLE, START, DATA, STOP = 0, 1, 2, 3
    def __init__(self):
        self.bg = BaudGen()
        self.state = self.IDLE
        self.bit_idx = 0
        self.shreg = 0
        self.tx_out = 1
        self.tx_done = 0
        self.start_req = 0
        self.start_data = 0
    def reset(self):
        self.bg.reset()
        self.state = self.IDLE
        self.bit_idx = 0
        self.shreg = 0
        self.tx_out = 1
        self.tx_done = 0
        self.start_req = 0
        self.start_data = 0
    def step(self, clk, rst_n, tx_start, data_in):
        self.tx_done = 0
        if clk and rst_n and tx_start:
            self.start_req = 1
            self.start_data = int(data_in) & 0xFF
        tick = self.bg.step(clk, rst_n)
        if not rst_n:
            self.reset()
            return self.tx_out, self.tx_done
        if not tick:
            return self.tx_out, self.tx_done
        if self.state == self.IDLE:
            if self.start_req:
                self.shreg = self.start_data
                self.bit_idx = 0
                self.state = self.START
                self.tx_out = 0
                self.start_req = 0
            else:
                self.tx_out = 1
        elif self.state == self.START:
            self.tx_out = (self.shreg >> 0) & 1
            self.bit_idx = 1
            self.state = self.DATA
        elif self.state == self.DATA:
            self.tx_out = (self.shreg >> self.bit_idx) & 1
            self.bit_idx += 1
            if self.bit_idx == 8:
                self.state = self.STOP
        elif self.state == self.STOP:
            self.tx_out = 1
            self.tx_done = 1
            self.state = self.IDLE
        return self.tx_out, self.tx_done

# Read input vectors
with open('tb/vecs/uart_tx_rst.mem') as f:
    v_rst = [int(line.strip()) for line in f if line.strip()]
with open('tb/vecs/uart_tx_start.mem') as f:
    v_tx_start = [int(line.strip()) for line in f if line.strip()]
with open('tb/vecs/uart_tx_data.mem') as f:
    v_data_in = [int(line.strip(), 16) for line in f if line.strip()]

# Simulate with OLD model
tx_old = UartTxOld()
tx_old.reset()
tx_old.step(1, 1, 1, 60)  # warmup -3
tx_old.step(1, 1, 0, 60)  # warmup -2
tx_old.step(1, 1, 0, 60)  # warmup -1

old_out = []
old_done = []
for i in range(20853):
    tx_out, tx_done = tx_old.step(1, v_rst[i], v_tx_start[i], v_data_in[i])
    old_out.append(tx_out)
    old_done.append(tx_done)

# Simulate with NEW model
from golden.model.uart_tx import UartTx
tx_new = UartTx()
tx_new.reset()
tx_new.step(1, 1, 1, 60)
tx_new.step(1, 1, 0, 60)
tx_new.step(1, 1, 0, 60)

new_out = []
new_done = []
for i in range(20853):
    tx_out, tx_done = tx_new.step(1, v_rst[i], v_tx_start[i], v_data_in[i])
    new_out.append(tx_out)
    new_done.append(tx_done)

# Compare
diffs = sum(1 for i in range(20853) if old_out[i] != new_out[i] or old_done[i] != new_done[i])
print(f"Differences between old and new golden model: {diffs}")

# Check first few differences
for i in range(20853):
    if old_out[i] != new_out[i] or old_done[i] != new_done[i]:
        print(f"  vec {i}: old(out={old_out[i]},done={old_done[i]}) new(out={new_out[i]},done={new_done[i]})")
        if diffs > 10:
            break