#!/usr/bin/env bash
# Write the resolv.conf file that is bind-mounted into the Strix rootless
# containers. Use this when podman-compose ignores Compose `dns:` and containers
# keep getting only the internal 10.89.x.1 resolver.
set -euo pipefail

OUT="${1:-container-resolv.conf}"
DNS1="${CONTAINER_DNS_1:-${2:-1.1.1.1}}"
DNS2="${CONTAINER_DNS_2:-${3:-8.8.8.8}}"

# If the caller explicitly asks for host DNS, copy non-loopback/non-podman
# nameservers from the host resolv.conf. This is useful on Tailscale/corporate
# networks where public DNS is blocked.
if [ "${USE_HOST_DNS:-0}" = "1" ]; then
  mapfile -t host_dns < <(awk '/^nameserver /{print $2}' /etc/resolv.conf | grep -vE '^(127\.|::1$|10\.89\.)' || true)
  if [ "${#host_dns[@]}" -ge 1 ]; then DNS1="${host_dns[0]}"; fi
  if [ "${#host_dns[@]}" -ge 2 ]; then DNS2="${host_dns[1]}"; fi
fi

cat > "$OUT" <<EOF
# Generated by scripts/write_container_resolv_conf.sh
# Bind-mounted into selected rootless Podman containers.
nameserver $DNS1
nameserver $DNS2
options timeout:2 attempts:2
EOF

echo "[dns] Wrote $OUT:"
cat "$OUT"
